function s_ms_plot_connectome_stats(trackingType)
% Load a connectome used for the Manuscript and plot some statistics on the
% fibers.
%
% See also: s_life_track.m,  s_lifeTestTractographyModels.m, 
%
%
% Copyright Franco Pestilli (2013) Vistasoft Stanford University.

%% Load the data
% Get the data path
dataDir  = msPaths('data');

% trackingType  = 'deterministic'; 
switch trackingType
  case {'deterministic'}
    connectomeFile = { ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000_2.mat', ...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000.mat',...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000_2.mat', ...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000_2.mat' ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000_2.mat', ...
      'fg_whole_brain_FACT_RK4.mat', ...
      'fg_whole_brain_TEND_RK4.mat', ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000_2_pointy.mat', ...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000_pointy.mat',...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000_2_pointy.mat', ...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000_2_pointy.mat' ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000_2_pointy.mat', ...
      'fg_whole_brain_FACT_RK4_pointy.mat', ...
      'fg_whole_brain_TEND_RK4_pointy.mat', ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000_fat.mat', ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000_2_fat.mat', ...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000_fat.mat',...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000_2_fat.mat', ...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000_fat.mat', ...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000_2_fat.mat' ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000_fat.mat', ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000_2_fat.mat', ...
      'fg_whole_brain_FACT_RK4_fat.mat', ...
      'fg_whole_brain_TEND_RK4_fat.mat'};
  case {'probabilistic'}
    connectomeFile = { ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000_2.mat', ...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000.mat',...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000_2.mat', ...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000_2.mat' ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000_2.mat', ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000_2_pointy.mat', ...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000_pointy.mat',...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000_2_pointy.mat', ...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000_2_pointy.mat' ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000_2_pointy.mat', ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000_fat.mat', ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000_2_fat.mat', ...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000_fat.mat',...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000_2_fat.mat', ...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000_fat.mat', ...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000_2_fat.mat' ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000_fat.mat', ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000_2_fat.mat'};
  otherwise
    keyboard
end

% Load one file at the time and make a histgram plot
for a = 1:length(connectomeFile)
    % Load the fe structure
    disp('Loading fe structure...')
    load(fullfile(dataDir,connectomeFile{a}));
    
    % Make a figure of the map.
    mapType  = 'maprep';
    
    plotType = 'voxr2';
    [~,h]  = fePlot(fe,mapType,plotType);   
    print(gcf,'-djpeg',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',mapType,'_',plotType]))
        
    plotType = 'voxr2voxelwise';
    [~,h] = fePlot(fe,mapType,plotType);
    print(gcf,'-djpeg',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',mapType,'_',plotType]))

    plotType = 'voxrmseratio';
    [~,h] = fePlot(fe,mapType,plotType);
    print(gcf,'-djpeg',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',mapType,'_',plotType]))

    plotType = 'voxrmseratiovoxelwise';
    [~,h] = fePlot(fe,mapType,plotType);
    print(gcf,'-djpeg',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',mapType,'_',plotType]))

    %% Plot measured signal
    plotType = 'dsigmeasured';
    [~,h] = fePlot(fe,plotType);
    print(gcf,'-depsc2',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',plotType]))

    %% Model fit.
    % RMSE
    plotType = 'rmse';
    [~,h] = fePlot(fe,plotType);
    set(gca,'ylim',[0 220],'xlim',[-1 100]);drawnow
    print(gcf,'-depsc2',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',plotType]))

    % Percent variance explained
    plotType = 'pve';
    [~,h] = fePlot(fe,plotType);
    set(gca,'ylim',[0 220],'xlim',[-200 100]);drawnow
    print(gcf,'-depsc2',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',plotType]))
    
    %% Cross validation.
    % RMSE
    plotType = 'rmserep';
    [~,h] = fePlot(fe,plotType);
    set(gca,'ylim',[0 220],'xlim',[-1 100]);drawnow
    print(gcf,'-depsc2',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',plotType]))
    
    % Percent variance explained
    plotType = 'pverep';
    [~,h] = fePlot(fe,plotType);
    set(gca,'ylim',[0 220],'xlim',[-200 100]);drawnow
    print(gcf,'-depsc2',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',plotType]))
    
    %% Data-2-data reliability
    % RMSE
    plotType = 'rmserepdata';
    [~,h] = fePlot(fe,plotType);
    set(gca,'ylim',[0 320],'xlim',[-1 100]);drawnow
    print(gcf,'-depsc2',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',plotType]))
    
    % Percent variance explained
    plotType = 'pve rep data';
    [~,h] = fePlot(fe,plotType);
    set(gca,'ylim',[0 220],'xlim',[-200 100]);drawnow
    print(gcf,'-depsc2',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',plotType]))
    
    %% Model-2-data comparison
    % RMSE
    plotType = 'rmseratio';
    [~,h] = fePlot(fe,plotType);
    set(gca,'ylim',[0 220],'xlim',[-0.5 2]);drawnow
    print(gcf,'-depsc2',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',plotType]))

    % Fiber length
    plotType = 'fiberlength';
    [~,h] = fePlot(fe,plotType);
    set(gca,'ylim',[0 1000],'xlim',[0 220]);drawnow
    print(gcf,'-depsc2',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_',plotType]))
    
    [~,h] = fePlot(fe,'connectome');
    print(gcf,'-djpeg',fullfile(feGet(fe,'savedir'),[connectomeFile{a}(1:end-4),'_FG']))

    close all; drawnow
end
