Description of feGet
Home > fe > feGet.m
feGet
PURPOSE
Get function for fascicle evaluation structure
SYNOPSIS
function val = feGet(fe,param,varargin)
DESCRIPTION
 Get function for fascicle evaluation structure
   val = feGet(fe,param,varargin)
 INPUTS:
  Coords    - Nx3 set of coordinates in image space
  voxelIndices - Vector of 1's and 0's, there is a one for each
              location the the connectome coordinates for which there is
              a match in the coords
 Copyright (2013-2014), Franco Pestilli & Brian Wandell,
  Stanford University, pestillifranco@gmail.com.
---------- List of arguments ----
 Name of the current fe structure.
 name = feGet(fe,'name')
----------
 The type of objes (always, fascicle evaluation)
 type = feGet(fe,'type')
----------
 Structure of parameters and results from LIFE analysis
 life = feGet(fe,'life')
----------
 Return the connectome (fiber group) in image coordinates.
 fg = feGEt(fe,'fg img')
----------
 return the connectome in acpc coordinates.
 fg  = feGet(fg,'fg acpc')
----------
 Return the VOI comprised by the full connectome.
 roi = feGet(fe,'roi')
----------
 Transforms between coords for fg, roi, and dwi data
 xform = feGet(fe,'xform')
----------
 Load the diffusion weighted data.
 dwi = feGet(fe,'dwi')
----------
 Return the path to the diffusion weighted data file.
 dwiFile = feGet(fe,'dwifile')
----------
 Load the repeated-measure diffusion weighted data.
 dwi = feGet(fe,'dwirepeat')
----------
 Load the repeated measure of the diffusion weighted data.
 dwiFile = feGet(fe,'dwirepeatfile')
----------
 Directory where the LiFe structes are saved by defualt.
 sdir = feGet(fe,'savedir');
----------
 Diffusion directions.
 val = feGet(fe,'bvecs');
----------
 Indices to the diffusion directions in the DWi 4th Dimension.
 val = feGet(fe,'bvecs indices');
----------
 Number of B0's
 val = feGet(fe,'n bvals');
----------
 B0 Values.
 bval = feGet(fe,'bvals')
----------
 Returns a nVoxels X nBvecs array of measured diffusion signal
 val = feGet(fe,'dsiinvox');
 val = feGet(fe,'dsiinvox',voxelsIndices);
 val = feGet(fe,'dsiinvox',coords);
----------
 Returns a nVoxels X nBvecs array of demeaned diffusion signal
 val =feGet(fe,'dsiinvoxdemeaned');
 val =feGet(fe,'dsiinvoxdemeaned',voxelsIndices);
 val =feGet(fe,'dsiinvoxdemeaned',coords);
----------
 Get the diffusion signal at 0 diffusion weighting (B0) for this voxel
 val = feGet(fe,'b0signalvoxel');
 val = feGet(fe,'b0signalvoxel',voxelIndex);
 val = feGet(fe,'b0signalvoxel',coords);
----------
 Return a subset of fibers from the conenctome.
 fg = feGet(fe,'fiberssubset',fiberList);
----------
 Return the coordinates of the VOI comprised in the connectome.
 Always in image space.
 coords = feGet(fe,'roi coords')
----------
 Number of voxels in the connectome/VOI.
 nVoxels = feGet(fe,'n voxels')
----------
 Indexes of actually used voxels.
 These can be different than the number of voxels in the VOI in case some
 voxels have no fibers in them.
 TO BE DEPRECATED.
 indxUsedVx = feGet(fe,'index of used voxels')
----------
 Number of actually used voxels.
 This can be less than the number of voxels in the VOI in case some
 voxels have no fibers in them.
 TO BE DEPRECATED.
 nUsedVx = feGet(fe,'index of used voxels')
----------
 Returns the first index to a voxel in the dSig vector.
 The dSig vector is 1:nBvecs*nVoxels.
 val = feGet(fe,'start rows')
----------
 Return the rows corresponding to a set of voxels.
 rows = feGet(fe,'voxel rows',idxVoxel)
----------
 Return the model (M matrix), or a subset of it.
 Mfiber = feGet(fe,'M fiber');
 Mfiber = feGet(fe,'model',voxelsIndices);
 Mfiber = feGet(fe,'model',coords);
----------
 Return a subset of measurements from the fiber portion of M matrix
 The rows of M are specified.  Remember that the rows refer to a
 combination of voxel and measurement direction and potentially in the
 future a b-value.  Hence, the rows are not specific to a voxel.
 Mfiber = feGet(fe,'mfiber subset',rowsToKeep);
----------
 Pairing of fibers and nodes in each voxel.
 v2fnp = feGet(fe,'v2fnp');
----------
 Tensors computed for each node and fiber in a set of voxels.
 t = feGet(fe,'tensors')
 t = feGet(fe,'tensors',voxelsIndices);
 t = feGet(fe,'tensors',coords);
----------
 Get all the tensors in a single voxel.
 val = feGet(fe,'voxtensors',voxelIndex)
 val = feGet(fe,'voxtensors',coord)
----------
 Returns the model (M) with only a subset of columns (fibers).
 fiberList is a vector of indexes, e.g, [1 10 100]
 M = feGet(fe,'keepfibers',fiberList)
----------
 Isotropic portion of M matrix. Returns the matrix for the full model or
 for a subset of voxels.
 Miso = feGet(fe,'M iso')
 Miso = feGet(fe,'M iso',voxelsIndices)
 Miso = feGet(fe,'M iso',coords)
----------
 Total number of nodes in each voxel The voxel2FN pairs are row size
 equals number of nodes and column size is always 2. The entries of
 the first column are the fiber number. The entries in the second
 column are the node of the fiber inside the voxel.
 val = feGet(fe,'n nodes');
 val = feGet(fe,'n nodes',voxelsIndices);
 val = feGet(fe,'n nodes',coords);
----------
 Return the total number of fibers for all the voxels or in a set of
 voxels.
 nFibers = feGet(fe,'uniquefnum');           % all the voxels
 nFibers = feGet(fe,'uniquefnum',[1 2 3 4]); % for some the voxels,
                                             % specified by indexes
 nFibers = feGet(fe,'uniquefnum',coords);    % for some the voxels,
                                             % specified by coordinates
----------
 Return the indexes of the fibers for all the voxels or in a set of
 voxels.
 idxFibers = feGet(fe,'uniquef');           % all the voxels
 idxFibers = feGet(fe,'uniquef',[1 2 3 4]); % for some the voxels,
                                            % specified by indexes
 idxFibers = feGet(fe,'uniquef',coords);    % for some the voxels,
                                            % specified by coordinates
----------
 Return the total number of fibers for all the voxels or in a set of
 voxels
 nFibers = feGet(fe,'totfnum');           % all the voxels
 nFibers = feGet(fe,'totfnum',[1 2 3 4]); % for some the voxels,
                                          % specified by indexes
 nFibers = feGet(fe,'totfnum',coords);    % for some the voxels,
                                          % specified by coordinates
----------
 Return the indexes of the fibers for all the voxels or in a set of
 voxels
 idxFibers = feGet(fe,'totf');             % all the voxels
 idxFibers = feGet(fe,'totf',[1 2 3 4]);   % for some the voxels,
                                           % specified by indexes
 idxFibers = feGet(fe,'totfibers',coords); % for some the voxels,
                                           % specified by coordinates
----------
 Return the number of fibers in the model.
 nFibers = feGet(fe,'n fibers');
----------
 Weights of the isotropic voxel signals, this is the mean signal in
 each voxel.
 val = feGet(fe,'iso weights');
 val = feGet(fe,'iso weights'coords)
 val = feGet(fe,'iso weights',voxelIndices)
----------
 Weights of the fiber component. For all the fibers or a subset of
 them.
 w = feGet(fe,'fiber weights')
 w = feGet(fe,'fiber weights',fiberIndices)
----------
 Weights of the fiber component with a subset of the fibers' weights
 set to zero. This can be used to test the loss in RMSE for the
 connectome when a subset of fibers is removed, but the connectome is
 not fitted again.
 w = feGet(fe,'fiber weights test',fiberIndices)
----------
 Predicted signal (demeaned) with a subset of fibers' weights set to 0.
 This can be used to test the loss in RMSE for the connectome when a
 subset of fibers is removed, but the connectome is not fitted again.
 pSig = feGet(fe,'pSig fiber test',fiberIndices);
 pSig = feGet(fe,'pSig fiber test',fiberIndices,voxelIndices);
 pSig = feGet(fe,'pSig fiber test',fiberIndices,coords);
----------
 Measured signal in VOI, this is the raw signal. not demeaned
 dSig = feGet(fe,'dSig full')
---------
 Measured signal in VOI, demeaned, this is the signal used for the
 fiber-portion of the M model.
 dSig = feGet(fe,'dsigdemeaned');
 dSig = feGet(fe,'dsigdemeaned',[1 10 100]);
 dSig = feGet(fe,'dsigdemeaned',coords);
---------
 Get the demeaned signal for a subset of rows.
 Useful for cross-validation.
 dSig = feGet(fe,'dsigrowssubset',voxelsList);
---------
 Predicted signal of fiber alone (demeaned).
 pSig = feGet(fe,'pSig fiber');
 pSig = feGet(fe,'pSig fiber',coords);
 pSig = feGet(fe,'pSig fiber',voxelIndices);
---------
 Predicted measured signal from both fiber and iso
 pSig = feGet(fe,'pSig full')
 pSig = feGet(fe,'pSig full',coords)
 pSig = feGet(fe,'pSig full',voxelIndices)
---------
 The woxels returned by a fit of LiFE by voxel/fiber
 w = feGet(fe,'fiberweightsvoxelwise')
---------
 Predict the diffusion signal for the fiber component
 with the voxel-wise fit of LiFE
 pSig = feGet(fe,'psigfvoxelwise')
 pSig = feGet(fe,'psigfvoxelwise',coords)
 pSig = feGet(fe,'psigfvoxelwise',voxelIndices)
---------
 Predict the diffusion signal for the fiber component
 with the voxel-wise fit of LiFE, return the an array of pSigXnVoxel
 pSig = feGet(fe,'psigfvoxelwisebyvoxel')
 pSig = feGet(fe,'psigfvoxelwisebyvoxel',coords)
 pSig = feGet(fe,'psigfvoxelwisebyvoxel',voxelIndices)
---------
 The fiber and isotropic weights as a long vector
 w = feGet(fe,'fullweights')
---------
 Return the global R2 (fraction of variance explained) of the full life
 model.
 R2 = feGet(fe,'total r2');
---------
 Percent variance explained
 R2 = feGet(fe,'explained variance')
---------
 Root mean squared error of the LiFE fit to the whole data
 rmse = feGet(fe,'rmse')
---------
 Residual signal: (fiber prediction - measured_demeaned).
 res = feGet(fe,'res sig fiber')
---------
 Residual signal: (full model prediction - measured signal).
 res = feGet(fe,'res sig full');
---------
 Residual signal: (fiber model prediction - demeaned measured signal)
 with added mean signal. Res is returned as a vector.
 This is used to reconstruct an image (volume) to be used for the
 refinement process.
 res = feGet(fe,'fiber res sig with mean');
 res = feGet(fe,'fiber res sig with mean',coords);
 res = feGet(fe,'fiber res sig with mean',voxelIndices);
---------
 Residual signal fiber model prediction - demeaned measured signal
 with added mean signal. Res is returned as an array (nBvecs x nVoxel).
 This is used to reconstruct an image (volume) to be used for the
 refinement process.
 res = feGet(fe,'fiber res sig with mean voxel');
 res = feGet(fe,'fiber res sig with mean voxel',coords);
 res = feGet(fe,'fiber res sig with mean voxel',voxelIndices);
---------
 Predicted signal by the fiber model in a set of voxels.
 Vox subfield stores per voxel within the VOI. The pSig has size of the
 dwi. - It is stored as val = pSig(X,Y,Z,Theta)
 pSig = feGet(fe, 'pSig fiber by voxel');
 pSig = feGet(fe, 'pSig fiber by voxel',coords);
 pSig = feGet(fe, 'pSig fiber by voxel',voxelIndex);
---------
 Return a column vector of the proportion of variance explained in
 each voxel.
 R2byVox = feGet(fe,'voxr2');
 R2byVox = feGet(fe,'voxr2',coords);
---------
 Return a column vector of the proportion of variance explained in
 each voxel. (Normalized to the squared mean diffusion signal in each voxel)
 R2byVox = feGet(fe,'voxr2zero');
 R2byVox = feGet(fe,'voxr2zero',coords);
---------
 Return the percent of varince explained in each voxel.
 R2byVox = feGet(fe,'var exp by voxel');
 R2byVox = feGet(fe,'var exp by voxel',coords);
---------
 Demeaned diffusion signal in each voxel.
 dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel');
 dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',coords);
 dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',vxIndex);
---------
 Full (measured) signal in each voxel.
 dSigByVoxel = feGet(fe,'dSig full by Voxel');
 dSigByVoxel = feGet(fe,'dSig full by Voxel',coords);
 dSigByVoxel = feGet(fe,'dSig full by Voxel',vxIndex);
---------
 Predicted signal by the full model in a set of voxeles.
 pSigByVoxel = feGet(fe, 'pSig full by voxel');
 pSigByVoxel = feGet(fe, 'pSig full by voxel',coords);
 pSigByVoxel = feGet(fe, 'pSig full by voxel',voxelIndex);
---------
 A volume of RMSE values.
 RMSE = feGet(fe,'vox rmse')
 RMSE = feGet(fe,'vox rmse',coords)
 RMSE = feGet(fe,'vox rmse',vxIndex)
---------
 A volume of RMSE values with a subset of fibers' weights set to 0.
 RMSE = feGet(fe,'vox rmse',fiberIndices)
 RMSE = feGet(fe,'vox rmse',fiberIndices,coords)
 RMSE = feGet(fe,'vox rmse',fiberIndices,voxelIndex)
---------
 Fibers' residual signal by voxel.
 res = feGet(fe,'res sig fiber vox')
 res = feGet(fe,'res sig fiber vox',coords)
 res = feGet(fe,'res sig fiber vox',vxIndex)
---------
 Full (measured) residual signal by voxel.
 res = feGet(fe,'res sig full vox')
 res = feGet(fe,'res sig full vox',coords)
 res = feGet(fe,'res sig full vox',vxIndex)
---------
 Fibers' residual signal by voxel with mean signal added (with added
 isotropic component).
 This is used to compute the residual signal for the refinement.
 res = feGet(fe,'fiber res sig with mean vox')
 res = feGet(fe,'fiber res sig with mean vox',coords)
 res = feGet(fe,'fiber res sig with mean vox',vxIndex)
---------
 Residual signal full model prediction from a multi-voxel fit.
 res = feGet(fe,'res sig full voxfit');
 res = feGet(fe, 'res sig full voxfit',coords);
 res = feGet(fe, 'res sig full voxfit',voxelIndex);
---------
 Fiber density statistics.
 Computes the fiber density (how many fibers in each voxel)
 We compute the following values:
 (1) The number of fibers in each voxel
 (2) The number of unique fibers with non-zero weights
 (3) The sum of the weights in each voxel
 (4) The mean of the weights in each voxel
 (5) The variance of the weigths in each voxel
 pSig = feGet(fe,'fiberdensity');
---------
 Given an VOI or a set of indices to voxels returns the indices of the matching voxels inside the big
 volume, which ordinarily represents the full connectome.
 voxelIndices = feGet(fe,'voxelsindices',coords)
                IMPORTANT: Size(coords) must be Nx3;
 voxelIndices = feGet(fe,'voxelsindices',voxelIndices)
                IMPORTANT: Indices MUST be a column vector for this
                code to work. Size(voxelIndices) = Nx1;
---------
 Given an VOI finds the indices of the matching voxels inside the big
 volume, which ordinarily represents the full connectome.
 foundVoxels = feGet(fe,'find voxels',coords)
 coords is a Nx3 set of coordinates in image space
 foundVoxels is a vector of 1's and 0's, there is a one for each
 location the the connectome coordinates for which there is a match in
 the coords
---------
 Given a set of VOI coords finds the row numbers of the Model matrix
 (or equivalently the dSig vector) that represent the data for this
 set of VOI coords.
 foundVoxels = feGet(fe,'coords 2 rows',coords)
 coords      - a Nx3 set of coordinates in image space
 foundVoxels - a binary vector that is 1 for each Model matrix row
               that corresponds to at least one of the coords.
---------
 Quaternian transformation from IMAGE space to ACPC space.
 xform = feGet(fe,'xform')
---------
 Quaternian transformation from ACPC space to IMAGE space.
 xform = feGet(fe,'xform')
---------
 Dimensions of the DW volume.
 dim = feGet(fe,'dims')
---------
 Dimensions of the maps of parameters and results.
 dims = feGet(fe, 'mapsize')
---------
 Path to the 3D Anatomy Volume.
 anatomyfile = feGet(fe, 't1 file')
 End of feGet.m parameters,
 Copyright (2013-2014), Franco Pestilli, Stanford University, pestillifranco@gmail.com.
CROSS-REFERENCE INFORMATION
This function calls:
feGet Get function for fascicle evaluation structure
feGetRep Get function for fascicle evaluation structure, to use for a repeated
This function is called by:
feConnectomeBuildModel Compute matrix to predict directional diffusion in each voxel from fibers
feConnectomeInit Initialize a new connectome (fe) structure.
feConnectomeReduceFibers Deletes a set of fibers from the signal and the M matrix.
feConnectomeReduceVoxels Select the voxels to keep (extract) in a connectome matrix
feConnectomeSelectFibers Deletes a set of fibers from the signal and the M matrix.
feConnectomeSetDwi Set all the fields necessary to store the DWI measurements.
feGet Get function for fascicle evaluation structure
feGetRep Get function for fascicle evaluation structure, to use for a repeated
feSet Set fascicle evaluation parameters.
feVirtualLesion Perform a virtual lesion.
SOURCE CODE
function val = feGet(fe,param,varargin)
% Get function for fascicle evaluation structure
%
%   val = feGet(fe,param,varargin)
%
%
% INPUTS:
%  Coords    - Nx3 set of coordinates in image space
%  voxelIndices - Vector of 1's and 0's, there is a one for each
%              location the the connectome coordinates for which there is
%              a match in the coords
%
%
% Copyright (2013-2014), Franco Pestilli & Brian Wandell,
%  Stanford University, pestillifranco@gmail.com.
%
%
%---------- List of arguments ----
% Name of the current fe structure.
% name = feGet(fe,'name')
%----------
% The type of objes (always, fascicle evaluation)
% type = feGet(fe,'type')
%----------
% Structure of parameters and results from LIFE analysis
% life = feGet(fe,'life')
%----------
% Return the connectome (fiber group) in image coordinates.
% fg = feGEt(fe,'fg img')
%----------
% return the connectome in acpc coordinates.
% fg  = feGet(fg,'fg acpc')
%----------
% Return the VOI comprised by the full connectome.
% roi = feGet(fe,'roi')
%----------
% Transforms between coords for fg, roi, and dwi data
% xform = feGet(fe,'xform')
%----------
% Load the diffusion weighted data.
% dwi = feGet(fe,'dwi')
%----------
% Return the path to the diffusion weighted data file.
% dwiFile = feGet(fe,'dwifile')
%----------
% Load the repeated-measure diffusion weighted data.
% dwi = feGet(fe,'dwirepeat')
%----------
% Load the repeated measure of the diffusion weighted data.
% dwiFile = feGet(fe,'dwirepeatfile')
%----------
% Directory where the LiFe structes are saved by defualt.
% sdir = feGet(fe,'savedir');
%----------
% Diffusion directions.
% val = feGet(fe,'bvecs');
%----------
% Indices to the diffusion directions in the DWi 4th Dimension.
% val = feGet(fe,'bvecs indices');
%----------
% Number of B0's
% val = feGet(fe,'n bvals');
%----------
% B0 Values.
% bval = feGet(fe,'bvals')
%----------
% Returns a nVoxels X nBvecs array of measured diffusion signal
% val = feGet(fe,'dsiinvox');
% val = feGet(fe,'dsiinvox',voxelsIndices);
% val = feGet(fe,'dsiinvox',coords);
%----------
% Returns a nVoxels X nBvecs array of demeaned diffusion signal
% val =feGet(fe,'dsiinvoxdemeaned');
% val =feGet(fe,'dsiinvoxdemeaned',voxelsIndices);
% val =feGet(fe,'dsiinvoxdemeaned',coords);
%----------
% Get the diffusion signal at 0 diffusion weighting (B0) for this voxel
% val = feGet(fe,'b0signalvoxel');
% val = feGet(fe,'b0signalvoxel',voxelIndex);
% val = feGet(fe,'b0signalvoxel',coords);
%----------
% Return a subset of fibers from the conenctome.
% fg = feGet(fe,'fiberssubset',fiberList);
%----------
% Return the coordinates of the VOI comprised in the connectome.
% Always in image space.
% coords = feGet(fe,'roi coords')
%----------
% Number of voxels in the connectome/VOI.
% nVoxels = feGet(fe,'n voxels')
%----------
% Indexes of actually used voxels.
% These can be different than the number of voxels in the VOI in case some
% voxels have no fibers in them.
%
% TO BE DEPRECATED.
% indxUsedVx = feGet(fe,'index of used voxels')
%----------
% Number of actually used voxels.
% This can be less than the number of voxels in the VOI in case some
% voxels have no fibers in them.
%
% TO BE DEPRECATED.
% nUsedVx = feGet(fe,'index of used voxels')
%----------
% Returns the first index to a voxel in the dSig vector.
% The dSig vector is 1:nBvecs*nVoxels.
% val = feGet(fe,'start rows')
%----------
% Return the rows corresponding to a set of voxels.
% rows = feGet(fe,'voxel rows',idxVoxel)
%----------
% Return the model (M matrix), or a subset of it.
% Mfiber = feGet(fe,'M fiber');
% Mfiber = feGet(fe,'model',voxelsIndices);
% Mfiber = feGet(fe,'model',coords);
%----------
% Return a subset of measurements from the fiber portion of M matrix
% The rows of M are specified.  Remember that the rows refer to a
% combination of voxel and measurement direction and potentially in the
% future a b-value.  Hence, the rows are not specific to a voxel.
% Mfiber = feGet(fe,'mfiber subset',rowsToKeep);
%----------
% Pairing of fibers and nodes in each voxel.
% v2fnp = feGet(fe,'v2fnp');
%----------
% Tensors computed for each node and fiber in a set of voxels.
% t = feGet(fe,'tensors')
% t = feGet(fe,'tensors',voxelsIndices);
% t = feGet(fe,'tensors',coords);
%----------
% Get all the tensors in a single voxel.
% val = feGet(fe,'voxtensors',voxelIndex)
% val = feGet(fe,'voxtensors',coord)
%----------
% Returns the model (M) with only a subset of columns (fibers).
% fiberList is a vector of indexes, e.g, [1 10 100]
% M = feGet(fe,'keepfibers',fiberList)
%----------
% Isotropic portion of M matrix. Returns the matrix for the full model or
% for a subset of voxels.
% Miso = feGet(fe,'M iso')
% Miso = feGet(fe,'M iso',voxelsIndices)
% Miso = feGet(fe,'M iso',coords)
%----------
% Total number of nodes in each voxel The voxel2FN pairs are row size
% equals number of nodes and column size is always 2. The entries of
% the first column are the fiber number. The entries in the second
% column are the node of the fiber inside the voxel.
% val = feGet(fe,'n nodes');
% val = feGet(fe,'n nodes',voxelsIndices);
% val = feGet(fe,'n nodes',coords);
%----------
% Return the total number of fibers for all the voxels or in a set of
% voxels.
% nFibers = feGet(fe,'uniquefnum');           % all the voxels
% nFibers = feGet(fe,'uniquefnum',[1 2 3 4]); % for some the voxels,
%                                             % specified by indexes
% nFibers = feGet(fe,'uniquefnum',coords);    % for some the voxels,
%                                             % specified by coordinates
%----------
% Return the indexes of the fibers for all the voxels or in a set of
% voxels.
% idxFibers = feGet(fe,'uniquef');           % all the voxels
% idxFibers = feGet(fe,'uniquef',[1 2 3 4]); % for some the voxels,
%                                            % specified by indexes
% idxFibers = feGet(fe,'uniquef',coords);    % for some the voxels,
%                                            % specified by coordinates
%----------
% Return the total number of fibers for all the voxels or in a set of
% voxels
% nFibers = feGet(fe,'totfnum');           % all the voxels
% nFibers = feGet(fe,'totfnum',[1 2 3 4]); % for some the voxels,
%                                          % specified by indexes
% nFibers = feGet(fe,'totfnum',coords);    % for some the voxels,
%                                          % specified by coordinates
%----------
% Return the indexes of the fibers for all the voxels or in a set of
% voxels
% idxFibers = feGet(fe,'totf');             % all the voxels
% idxFibers = feGet(fe,'totf',[1 2 3 4]);   % for some the voxels,
%                                           % specified by indexes
% idxFibers = feGet(fe,'totfibers',coords); % for some the voxels,
%                                           % specified by coordinates
%----------
% Return the number of fibers in the model.
% nFibers = feGet(fe,'n fibers');
%----------
% Weights of the isotropic voxel signals, this is the mean signal in
% each voxel.
% val = feGet(fe,'iso weights');
% val = feGet(fe,'iso weights'coords)
% val = feGet(fe,'iso weights',voxelIndices)
%----------
% Weights of the fiber component. For all the fibers or a subset of
% them.
% w = feGet(fe,'fiber weights')
% w = feGet(fe,'fiber weights',fiberIndices)
%----------
% Weights of the fiber component with a subset of the fibers' weights
% set to zero. This can be used to test the loss in RMSE for the
% connectome when a subset of fibers is removed, but the connectome is
% not fitted again.
% w = feGet(fe,'fiber weights test',fiberIndices)
%----------
% Predicted signal (demeaned) with a subset of fibers' weights set to 0.
% This can be used to test the loss in RMSE for the connectome when a
% subset of fibers is removed, but the connectome is not fitted again.
%
% pSig = feGet(fe,'pSig fiber test',fiberIndices);
% pSig = feGet(fe,'pSig fiber test',fiberIndices,voxelIndices);
% pSig = feGet(fe,'pSig fiber test',fiberIndices,coords);
%----------
% Measured signal in VOI, this is the raw signal. not demeaned
%
% dSig = feGet(fe,'dSig full')
%---------
% Measured signal in VOI, demeaned, this is the signal used for the
% fiber-portion of the M model.
%
% dSig = feGet(fe,'dsigdemeaned');
% dSig = feGet(fe,'dsigdemeaned',[1 10 100]);
% dSig = feGet(fe,'dsigdemeaned',coords);
%---------
% Get the demeaned signal for a subset of rows.
% Useful for cross-validation.
% dSig = feGet(fe,'dsigrowssubset',voxelsList);
%---------
% Predicted signal of fiber alone (demeaned).
% pSig = feGet(fe,'pSig fiber');
% pSig = feGet(fe,'pSig fiber',coords);
% pSig = feGet(fe,'pSig fiber',voxelIndices);
%---------
% Predicted measured signal from both fiber and iso
% pSig = feGet(fe,'pSig full')
% pSig = feGet(fe,'pSig full',coords)
% pSig = feGet(fe,'pSig full',voxelIndices)
%---------
% The woxels returned by a fit of LiFE by voxel/fiber
% w = feGet(fe,'fiberweightsvoxelwise')
%---------
% Predict the diffusion signal for the fiber component
% with the voxel-wise fit of LiFE
% pSig = feGet(fe,'psigfvoxelwise')
% pSig = feGet(fe,'psigfvoxelwise',coords)
% pSig = feGet(fe,'psigfvoxelwise',voxelIndices)
%---------
% Predict the diffusion signal for the fiber component
% with the voxel-wise fit of LiFE, return the an array of pSigXnVoxel
% pSig = feGet(fe,'psigfvoxelwisebyvoxel')
% pSig = feGet(fe,'psigfvoxelwisebyvoxel',coords)
% pSig = feGet(fe,'psigfvoxelwisebyvoxel',voxelIndices)
%---------
% The fiber and isotropic weights as a long vector
% w = feGet(fe,'fullweights')
%---------
% Return the global R2 (fraction of variance explained) of the full life
% model.
% R2 = feGet(fe,'total r2');
%---------
% Percent variance explained
% R2 = feGet(fe,'explained variance')
%---------
% Root mean squared error of the LiFE fit to the whole data
% rmse = feGet(fe,'rmse')
%---------
% Residual signal: (fiber prediction - measured_demeaned).
% res = feGet(fe,'res sig fiber')
%---------
% Residual signal: (full model prediction - measured signal).
% res = feGet(fe,'res sig full');
%---------
% Residual signal: (fiber model prediction - demeaned measured signal)
% with added mean signal. Res is returned as a vector.
% This is used to reconstruct an image (volume) to be used for the
% refinement process.
% res = feGet(fe,'fiber res sig with mean');
% res = feGet(fe,'fiber res sig with mean',coords);
% res = feGet(fe,'fiber res sig with mean',voxelIndices);
%---------
% Residual signal fiber model prediction - demeaned measured signal
% with added mean signal. Res is returned as an array (nBvecs x nVoxel).
% This is used to reconstruct an image (volume) to be used for the
% refinement process.
% res = feGet(fe,'fiber res sig with mean voxel');
% res = feGet(fe,'fiber res sig with mean voxel',coords);
% res = feGet(fe,'fiber res sig with mean voxel',voxelIndices);
%---------
% Predicted signal by the fiber model in a set of voxels.
% Vox subfield stores per voxel within the VOI. The pSig has size of the
% dwi. - It is stored as val = pSig(X,Y,Z,Theta)
%
% pSig = feGet(fe, 'pSig fiber by voxel');
% pSig = feGet(fe, 'pSig fiber by voxel',coords);
% pSig = feGet(fe, 'pSig fiber by voxel',voxelIndex);
%---------
% Return a column vector of the proportion of variance explained in
% each voxel.
% R2byVox = feGet(fe,'voxr2');
% R2byVox = feGet(fe,'voxr2',coords);
%---------
% Return a column vector of the proportion of variance explained in
% each voxel. (Normalized to the squared mean diffusion signal in each voxel)
% R2byVox = feGet(fe,'voxr2zero');
% R2byVox = feGet(fe,'voxr2zero',coords);
%---------
% Return the percent of varince explained in each voxel.
% R2byVox = feGet(fe,'var exp by voxel');
% R2byVox = feGet(fe,'var exp by voxel',coords);
%---------
% Demeaned diffusion signal in each voxel.
% dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel');
% dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',coords);
% dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',vxIndex);
%---------
% Full (measured) signal in each voxel.
% dSigByVoxel = feGet(fe,'dSig full by Voxel');
% dSigByVoxel = feGet(fe,'dSig full by Voxel',coords);
% dSigByVoxel = feGet(fe,'dSig full by Voxel',vxIndex);
%---------
% Predicted signal by the full model in a set of voxeles.
% pSigByVoxel = feGet(fe, 'pSig full by voxel');
% pSigByVoxel = feGet(fe, 'pSig full by voxel',coords);
% pSigByVoxel = feGet(fe, 'pSig full by voxel',voxelIndex);
%---------
% A volume of RMSE values.
% RMSE = feGet(fe,'vox rmse')
% RMSE = feGet(fe,'vox rmse',coords)
% RMSE = feGet(fe,'vox rmse',vxIndex)
%---------
% A volume of RMSE values with a subset of fibers' weights set to 0.
% RMSE = feGet(fe,'vox rmse',fiberIndices)
% RMSE = feGet(fe,'vox rmse',fiberIndices,coords)
% RMSE = feGet(fe,'vox rmse',fiberIndices,voxelIndex)
%---------
% Fibers' residual signal by voxel.
% res = feGet(fe,'res sig fiber vox')
% res = feGet(fe,'res sig fiber vox',coords)
% res = feGet(fe,'res sig fiber vox',vxIndex)
%---------
% Full (measured) residual signal by voxel.
% res = feGet(fe,'res sig full vox')
% res = feGet(fe,'res sig full vox',coords)
% res = feGet(fe,'res sig full vox',vxIndex)
%---------
% Fibers' residual signal by voxel with mean signal added (with added
% isotropic component).
% This is used to compute the residual signal for the refinement.
% res = feGet(fe,'fiber res sig with mean vox')
% res = feGet(fe,'fiber res sig with mean vox',coords)
% res = feGet(fe,'fiber res sig with mean vox',vxIndex)
%---------
% Residual signal full model prediction from a multi-voxel fit.
% res = feGet(fe,'res sig full voxfit');
% res = feGet(fe, 'res sig full voxfit',coords);
% res = feGet(fe, 'res sig full voxfit',voxelIndex);
%---------
% Fiber density statistics.
% Computes the fiber density (how many fibers in each voxel)
% We compute the following values:
% (1) The number of fibers in each voxel
% (2) The number of unique fibers with non-zero weights
% (3) The sum of the weights in each voxel
% (4) The mean of the weights in each voxel
% (5) The variance of the weigths in each voxel
% pSig = feGet(fe,'fiberdensity');
%---------
% Given an VOI or a set of indices to voxels returns the indices of the matching voxels inside the big
% volume, which ordinarily represents the full connectome.
% voxelIndices = feGet(fe,'voxelsindices',coords)
%                IMPORTANT: Size(coords) must be Nx3;
% voxelIndices = feGet(fe,'voxelsindices',voxelIndices)
%                IMPORTANT: Indices MUST be a column vector for this
%                code to work. Size(voxelIndices) = Nx1;
%---------
% Given an VOI finds the indices of the matching voxels inside the big
% volume, which ordinarily represents the full connectome.
%
% foundVoxels = feGet(fe,'find voxels',coords)
%
% coords is a Nx3 set of coordinates in image space
% foundVoxels is a vector of 1's and 0's, there is a one for each
% location the the connectome coordinates for which there is a match in
% the coords
%---------
% Given a set of VOI coords finds the row numbers of the Model matrix
% (or equivalently the dSig vector) that represent the data for this
% set of VOI coords.
% foundVoxels = feGet(fe,'coords 2 rows',coords)
% coords      - a Nx3 set of coordinates in image space
% foundVoxels - a binary vector that is 1 for each Model matrix row
%               that corresponds to at least one of the coords.
%---------
% Quaternian transformation from IMAGE space to ACPC space.
% xform = feGet(fe,'xform')
%---------
% Quaternian transformation from ACPC space to IMAGE space.
% xform = feGet(fe,'xform')
%---------
% Dimensions of the DW volume.
% dim = feGet(fe,'dims')
%---------
% Dimensions of the maps of parameters and results.
% dims = feGet(fe, 'mapsize')
%---------
% Path to the 3D Anatomy Volume.
% anatomyfile = feGet(fe, 't1 file')
%
% End of feGet.m parameters,
%
% Copyright (2013-2014), Franco Pestilli, Stanford University, pestillifranco@gmail.com.
val = [];
% Format the input parameters.
param = lower(strrep(param,' ',''));
% Start sorting the input and computing the output.
switch param
  case 'name'
    % Name of the current fe structure.
    %
    % name = feGet(fe,'name')
    val = fe.name;
  case 'type'
    % The type of objes (always, fascicle evaluation)
    %
    % type = feGet(fe,'type')
    val = fe.type; % Always fascicle evaluation
    % Set top level structure, not just single slot
  case 'life'
    % Structure of parameters and results from LIFE analysis
    %
    % life = feGet(fe,'life')
    val = fe.life;
  case {'fgimg','fibersimg'}
    % Return the connectome (fiber group) in image coordinates.
    %
    % fg = feGet(fe,'fg img')
    val = fe.fg;  % Fiber group candidate fascicles, uses fgSet/Get
  case {'fgacpc','fibersacpc'}
    % return the connectome in acpc coordinates.
    %
    % fg  = feGet(fg,'fg acpc')
    xform = feGet(fe,'img2acpcxform');
    val   = dtiXformFiberCoords(feGet(fe,'fgimg'),xform,'acpc');
  case 'roi'
    % Return the VOI comprised by the full connectome.
    %
    % roi = feGet(fe,'roi')
    val = fe.roi;
  case 'roiacpc'
    % Return the VOI comprised by the full connectome.
    %
    % roi = feGet(fe,'roi acpc')
    name   = sprintf('roi_%s',fe.fg.name);
    randColor = rand(1,3);
    val = dtiNewRoi(name,randColor,fefgGet(feGet(fe,'fg acpc'),'unique image coords'));
  case 'xform'
    % Transforms between coords for fg, roi, and dwi data
    %
    % xform = feGet(fe,'xform')
    val = fe.life.xform;
  case 'dwi'
    %  Load the diffusion weighted data.
    %
    % dwi = feGet(fe,'dwi')
    val = dwiLoad(feGet(fe,'dwifile'));
  case 'dwirepeat'
    %  Load the diffusion weighted data.
    %
    % dwi = feGet(fe,'dwirepeat')
    val = dwiLoad(feGetRep(fe,'dwifile'));
  case 'dwifile'
    %  Load the diffusion weighted data.
    %
    % dwiFile = feGet(fe,'dwifile')
    val = fe.path.dwifile;
  case 'dwifilerep'
    %  Load the diffusion weighted data.
    %
    % dwiFile = feGet(fe,'dwifilerep')
    val = fe.path.dwifilerep;
  case 'savedir'
    %  Directory where the LiFe structes are saved by defualt.
    %
    % sdir = feGet(fe,'savedir');
    val = fe.path.savedir;
  case {'bvecs'}
    % Diffusion directions.
    %
    % val = feGet(fe,'bvecs');
    val = fe.life.bvecs;
  case {'bvecsindices'}
    % Indices to the diffusion directions in the DWi 4th Dimension.
    %
    % val = feGet(fe,'bvecs indices');
    val = fe.life.bvecsindices;
  case {'nbvecs','nbvals'}
    % Number of B0's
    %
    % val = feGet(fe,'n bvals');
    val = length(feGet(fe,'bvals'));
  case {'bvals'}
    % B0 Values.
    %
    % bval = feGet(fe,'bvals')
    val = fe.life.bvals;
  case {'diffusionsignalinvoxel','dsiinvox','dsigvox','dsigmeasuredvoxel'}
    % Returns a nVoxels X nBvecs array of measured diffusion signal
    %
    % val = feGet(fe,'dsiinvox');
    % val = feGet(fe,'dsiinvox',voxelsIndices);
    % val = feGet(fe,'dsiinvox',coords);
    val = fe.life.diffusion_signal_img(feGet(fe,'voxelsindices',varargin),:)';
  case {'diffusionsignalinvoxeldemeaned','dsiinvoxdemeaned'}
    % Returns a nVoxels X nBvecs array of demeaned diffusion signal
    %
    % val =feGet(fe,'dsiinvoxdemeaned');
    % val =feGet(fe,'dsiinvoxdemeaned',voxelsIndices);
    % val =feGet(fe,'dsiinvoxdemeaned',coords);
    nBvecs     = feGet(fe,'nBvecs');
    voxelIndices = feGet(fe,'voxelsindices',varargin);
    val = fe.life.diffusion_signal_img(voxelIndices,:) - repmat(mean(fe.life.diffusion_signal_img(voxelIndices,:), 2),1,nBvecs);
    keyboard
    % THis seems to be wrong
  case {'b0signalimage','b0vox'}
    % Get the diffusion signal at 0 diffusion weighting (B0) for this voxel
    %
    % val = feGet(fe,'b0signalvoxel');
    % val = feGet(fe,'b0signalvoxel',voxelIndex);
    % val = feGet(fe,'b0signalvoxel',coords);
    val = fe.life.diffusion_S0_img(feGet(fe,'voxelsindices',varargin), :);
  case {'fiberssubset','fsub','subsetoffibers','fgsubset'}
    % Return a subset of fibers from the conenctome.
    %
    % fg = feGet(fe,'fiberssubset',fiberList);
    val = feGet(fe,'fg img');
    fiberList = varargin{1};
    fibers = cell(size(fiberList));
    for ff = 1:length(fiberList)
      fibers{ff} = val.fibers{fiberList(ff)};
      if isfield(val,'pathwayInfo')
        pathInfo(ff) = val.pathwayInfo(fiberList(ff));
      end
    end
    val.fibers = fibers;
    if isfield(val,'pathwayInfo')
      val.pathwayInfo = pathInfo;
    end
    val.name = sprintf('subsetFrom:%s',val.name);
  case {'roivoxels','roicoords'}
    % Return the coordinates of the VOI comprised in the connectome.
    % Always in image space.
    %
    % coords = feGet(fe,'roi coords')
    val = fe.roi.coords;
  case {'roicoordssubset'}
    % Return the coordinates of the VOI comprised in the connectome.
    % Always in image space.
    %
    % coords = feGet(fe,'roi coords')
    val = feGet(fe,'roi coords');
    val = val(varargin{1},:);
  case {'nroivoxels','nvoxels'}
    % Number of voxels in the connectome/VOI.
    %
    % nVoxels = feGet(fe,'n voxels')
    val = size(feGet(fe,'roivoxels'),1);
  case {'usedvoxels','indexesofusedvoxels'}
    % Indexes of actually used voxels.
    %
    % These can be different than the number of voxels in the VOI in case some
    % voxels have no fibers in them.
    %
    % TO BE DEPRECATED.
    %
    % indxUsedVx = feGet(fe,'index of used voxels')
    val = find(feGet(fe,'nnodes'));
  case {'nusedvoxels','numberofusedvoxels'}
    % Number of actually used voxels.
    %
    % This can be less than the number of voxels in the VOI in case some
    % voxels have no fibers in them.
    %
    % TO BE DEPRECATED.
    %
    % nUsedVx = feGet(fe,'index of used voxels')
    val = size(feGet(fe,'used voxels'),2);
  case {'startrow','first index into the dsig vector for a voxel'}
    % Returns the first index to a voxel in the dSig vector.
    %
    % The dSig vector is 1:nBvecs*nVoxels.
    %
    % val = feGet(fe,'start rows')
    val = (varargin{1}-1)*feGet(fe,'nBvecs') + 1;
  case {'voxelrows','all indexes into the dsig vector for a set of voxels'}
    % Return the rows corresponding to a set of voxels.
    %
    % rows = feGet(fe,'voxel rows',idxVoxel)
    n        = feGet(fe,'n voxels');
    nBvecs   = feGet(fe,'n bvecs');
    voxelsToKeep = zeros(n,1); voxelsToKeep(varargin{1}) = 1;
    val = logical(kron(voxelsToKeep(:),ones(nBvecs,1)));
  case {'modeltensor'}
    val = fe.life.modelTensor;
  case {'mfiber','m','model'}
    % Return the model (M matrix), or a subset of it.
    %
    % Mfiber = feGet(fe,'M fiber');
    % Mfiber = feGet(fe,'model',voxelsIndices);
    % Mfiber = feGet(fe,'model',coords);
    % idxVoxels is an integer list of the voxels to retain
    % If idxVoxels is not included, return the whole matrix
    % M contains only the rows for the specified voxels (all directions)
    if isempty(varargin)
      % Return the whole M matrix
      val = fe.life.Mfiber;
    else
      % Return only the rows for the specified voxels, including all
      % directions.
      % voxelIndices     = feGet(fe,'voxelsindices',varargin);
      % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
      % val = fe.life.Mfiber(voxelRowsToKeep,:);
      val = fe.life.Mfiber(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)),:);
    end
  case {'mfibervoxelsubset','indexedafiber','mfiberindexed'}
    % Return a subset of measurements from the fiber portion of M matrix
    % The rows of M are specified.  Remember that the rows refer to a
    % combination of voxel and measurement direction and potentially in the
    % future a b-value.  Hence, the rows are not specific to a voxel.
    %
    % Mfiber = feGet(fe,'mfiber subset',rowsToKeep);
    if isempty(varargin), error('Subset of rows must be specified'); end
    val = fe.life.Mfiber(varargin{1},:);
  case {'msubsetfibers','mfiberssubset','mkeepfibers'}
    % Returns the model (M) with only a subset of columns (fibers).
    %
    % fiberList is a vector of indexes, e.g, [1 10 100]
    %
    % M = feGet(fe,'mkeepfibers',fiberList)
    val = fe.life.Mfiber(:,varargin{1});
  case {'miso'}
    % Isotropic portion of M matrix
    % returns the matrix for the full model or for a subset of voxels
    %
    % Miso = feGet(fe,'M iso')
    % Miso = feGet(fe,'M iso',voxelsIndices)
    % Miso = feGet(fe,'M iso',coords)
    if isempty(varargin)
      % Return the whole M iso
      val = feBuildSparseBlockDiag(feGet(fe,'nBvecs'),feGet(fe,'nVoxels'));
    else
      val = feBuildSparseBlockDiag(feGet(fe,'nBvecs'),length(feGet(fe,'voxelsindices',varargin)));
    end
  case {'voxel2fnpair','voxel2fibernodepair','v2fnp'}
    % Pairing of fibers and nodes in each voxel.
    %
    % v2fnp = feGet(fe,'v2fnp');
    if isempty(fe.life.voxel2FNpair)
      fprintf('[%s] fe.life.voxel2FNpair is empty, can be computed as: \nfe = feSet(fe,''v2fnp'',feGet(fe,''fg img''),''v2fn'',feGet(fe,''roi coords'')',mfilename);
      return
    end
    val = fe.life.voxel2FNpair;
  case {'tensors','fibers tensors'}
    % Tensors computed for each node and fiber in a set of voxels.
    %
    % t = feGet(fe,'tensors')
    % t = feGet(fe,'tensors',voxelsIndices);
    % t = feGet(fe,'tensors',coords);
    if isempty(varargin)
      val = fe.life.fibers.tensors;
    else
      vv = feGet(fe,'voxelsindices',varargin);
      val = cell(size(vv));
      for ff = 1:length(vv)
        val{ff} = fe.life.fibers.tensors{vv(ff)};
      end
    end
  case {'voxeltensors','voxtensors','voxq'}
    % Get all the tensors in a signle voxel
    %
    % val = feGet(fe,'voxtensors',voxelIndex)
    % val = feGet(fe,'voxtensors',coord)
    % Index for the voxel
    vv = feGet(fe,'voxelsindices',varargin);
    % The indexes of the voxeles used, to build LiFE.
    usedVoxels = feGet(fe,'usedVoxels');
    voxIndex   = usedVoxels(vv);
    nNodes     = feGet(fe,'nNodes');
    % Get the tensors for each node in each fiber going through this voxel:
    val = zeros(nNodes(voxIndex), 9); % Allocate space for all the tensors (9 is for the 3 x 3 tensor components)
    for ii = 1:nNodes(voxIndex)           % Get the tensors
      val(ii,:) = fe.life.fibers.tensors{fe.life.voxel2FNpair{voxIndex}(ii,1)} ...
        (fe.life.voxel2FNpair{voxIndex}(ii,2),:);
    end
  case {'nnodes','numofnodes'}
    % Total number of nodes in each voxel The voxel2FN pairs are row size
    % equals number of nodes and column size is always 2. The entries of
    % the first column are the fiber number. The entries in the second
    % column are the node of the fiber inside the voxel.
    %
    % val = feGet(fe,'n nodes');
    % val = feGet(fe,'n nodes',voxelsIndices);
    % val = feGet(fe,'n nodes',coords);
    if ~isempty(fe.life.voxel2FNpair)
        [val, ~] = cellfun(@size,fe.life.voxel2FNpair);
        val      = val(feGet(fe,'voxelsindices',varargin));
    end
  case {'numberofuniquefibersbyvoxel','uniquefnum'}
    % Return the total number of fibers for all the voxels or in a set of
    % voxels
    %
    % nFibers = feGet(fe,'uniquefnum');           % all the voxels
    % nFibers = feGet(fe,'uniquefnum',[1 2 3 4]); % for some the voxels,
    %                                             % specified by indexes
    % nFibers = feGet(fe,'uniquefnum',coords);    % for some the voxels,
    %                                             % specified by coordinates
    val = fe.life.fibers.unique.num(feGet(fe,'voxelsindices',varargin));
  case {'indextouniquefibersbyvoxel','uniquef'}
    % Return the indexes of the fibers for all the voxels or in a set of
    % voxels.
    %
    % idxFibers = feGet(fe,'uniquef');           % all the voxels
    % idxFibers = feGet(fe,'uniquef',[1 2 3 4]); % for some the voxels,
    %                                            % specified by indexes
    % idxFibers = feGet(fe,'uniquef',coords);    % for some the voxels,
    %                                            % specified by coordinates
    vxIndex = feGet(fe,'voxels indices',varargin);
    val = cell(length(vxIndex),1);
    for ii = 1:length(vxIndex)
      val{ii} = fe.life.fibers.unique.index{vxIndex(ii)};
    end
  case {'numberoftotalfibersbyvoxels','totfnum'}
    % Return the total number of fibers for all the voxels or in a set of
    % voxels
    %
    % nFibers = feGet(fe,'totfnum');           % all the voxels
    % nFibers = feGet(fe,'totfnum',[1 2 3 4]); % for some the voxels,
    %                                          % specified by indexes
    % nFibers = feGet(fe,'totfnum',coords);    % for some the voxels,
    %                                          % specified by coordinates
    val = fe.life.fibers.total.num(feGet(fe,'voxels indices',varargin));
  case {'indexoftotalfibersbuvoxel','totf'}
    % Return the indexes of the fibers for all the voxels or in a set of
    % voxels
    %
    % idxFibers = feGet(fe,'totf');             % all the voxels
    % idxFibers = feGet(fe,'totf',[1 2 3 4]);   % for some the voxels,
    %                                           % specified by indexes
    % idxFibers = feGet(fe,'totfibers',coords); % for some the voxels,
    %                                           % specified by coordinates
    vxIndex = feGet(fe,'voxels indices',varargin);
    val = cell(length(vxIndex),1);
    for ii = 1:length(vxIndex)
      val{ii} = fe.life.fibers.total.index{vxIndex(ii)};
    end
  case {'nfibers'}
    % Return the number of fibers in the model.
    %
    % nFibers = feGet(fe,'n fibers')
    val = size(fe.life.Mfiber,2);
  case {'isoweights','weightsiso','meanvoxelsignal'}
    % Weights of the isotropic voxel signals, this is the mean signal in
    % each voxel.
    %
    % val = feGet(fe,'iso weights');
    % val = feGet(fe,'iso weights'coords)
    % val = feGet(fe,'iso weights',voxelIndices)
    val = feGet(fe,'Miso') \ feGet(fe,'dsig full')';
    val = val(feGet(fe,'voxelsindices',varargin));
  case {'voxisoweights','voxweightsiso','voxmeanvoxelsignal'}
    % Weights of the isotropic voxel signals, this is the mean signal in
    % each voxel.
    % Organized nBvecs x nVoxels
    %
    % val = feGet(fe,'iso weights');
    % val = feGet(fe,'iso weights'coords)
    % val = feGet(fe,'iso weights',voxelIndices)
    val = feGet(fe,'Miso') \ feGet(fe,'dsig full')';
    val = repmat(val,1,feGet(fe,'nbvecs'))';
    if ~isempty(varargin)
      % voxelIndices     = feGet(fe,'voxelsindices',varargin);
      % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
      % val           = val(voxelRowsToKeep,:);
      val = val(:,feGet(fe,'voxelsindices',varargin));
    end
  case {'dsigiso','isodsig'}
    % mean signalin each voxel, returned for each diffusion direction:
    % size(nBvecsxnVoxels, 1).
    %
    % val = feGet(fe,'iso disg');
    % val = feGet(fe,'iso disg',coords)
    % val = feGet(fe,'iso dsig',voxelIndices)
    val = feGet(fe,'iso weights');
    val = repmat(val,1,feGet(fe,'nbvecs'))';
    val = val(:);
  case {'fiberweights'}
    % Weights of the fiber component. For all the fibers or a subset of
    % them.
    %
    % w = feGet(fe,'fiber weights')
    % w = feGet(fe,'fiber weights',fiberIndices)
    % If the model was not fit yet, fit it, install the fit and then return
    % the weights.
    if ~isfield(fe.life,'fit')
      fprintf('[%s] fe.life.fit is empty, can be computed as: \nfeSet(fe,''fit'',feFitModel(feGet(fe,''Mfiber''), feGet(fe,''dsigdemeaned''),''sgdnn''))',mfilename);
      return
    end
    % Get the weights
    if ~isempty(varargin) % subselect the weights for the requested fibers
      val = fe.life.fit.weights(varargin{1});
    else % Return all of them
      val = fe.life.fit.weights;
    end
  case {'fiberweightstest'}
    % Weights of the fiber component with a subset of the fibers' weigth
    % set to zero. This can be used to test the loss in RMSE for the
    % connectome when a subset of fibers is removed, but the connectome is
    % not fitted again.
    %
    % w = feGet(fe,'fiber weights test',fiberIndices)
    % If the model was not fit yet, fit it, install the fit and then return
    % the weights.
    if ~isfield(fe.life,'fit')
      fprintf('[%s] fe.life.fit is empty, can be computed as: \nfeSet(fe,''fit'',feFitModel(feGet(fe,''Mfiber''), feGet(fe,''dsigdemeaned''),''sgdnn''))',mfilename);
      return
    end
    % Get the weights
    if ~isempty(varargin) % subselect the weights for the requested fibers
      val = fe.life.fit.weights;
      val(varargin{1}) = 0;
    else % A set of fiber weights is required as input
      error('[%s] Indices to a subset of fiber-weights must be passed in w = feGet(fe,''fiber weights test'',fiberIndices))',mfilename);
    end
    case {'fiberweightstestvoxelwise'}
    % Weights of the fiber component with a subset of the fibers' weigth
    % set to zero. This can be used to test the loss in RMSE for the
    % connectome when a subset of fibers is removed, but the connectome is
    % not fitted again.
    %
    % w = feGet(fe,'fiber weights test voxel wise',fiberIndices)
    % If the model was not fit yet, fit it, install the fit and then return
    % the weights.
    if ~isfield(fe.life,'voxfit')
      fprintf('[%s] fe.life.fit is empty, can be computed as: \nfeSet(fe,''fit'',feFitModel(feGet(fe,''Mfiber''), feGet(fe,''dsigdemeaned''),''sgdnn''))',mfilename);
      return
    end
    % Get the weights
    if ~isempty(varargin) % subselect the weights for the requested fibers
      val = fe.life.voxfit.weights;
      val(:,varargin{1}) = 0;
    else % A set of fiber weights is required as input
      error('[%s] Indices to a subset of fiber-weights must be passed in\nw = feGet(fe,''fiber weights test voxel wise'',fiberIndices))',mfilename);
    end
  case {'dsigmeasured','dsigfull'}
    % Measured signal in VOI, this is the raw signal. not demeaned
    %
    % dSig = feGet(fe,'dSig full')
    val = fe.life.dSig;
    % Return a subset of voxels
    if ~isempty(varargin)
      % voxelIndices     = feGet(fe,'voxelsindices',varargin);
      % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
      % val              = val(voxelRowsToKeep,:);
      val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
    end
  case {'diffusionsignaldemeaned','dsigdemeaned'}
    % Measured signal in VOI, demeaned, this is the signal used for the
    % fiber-portion of the M model.
    %
    % dSig = feGet(fe,'dsigdemeaned');
    % dSig = feGet(fe,'dsigdemeaned',[1 10 100]);
    % dSig = feGet(fe,'dsigdemeaned',coords);
    nVoxels = feGet(fe,'nVoxels');
    nBvecs  = feGet(fe,'nBvecs');
    val     = (fe.life.dSig - reshape(repmat( ...
      mean(reshape(fe.life.dSig, nBvecs, nVoxels),1),...
      nBvecs,1), size(fe.life.dSig)))';
    % Return a subset of voxels
    if ~isempty(varargin)
      % voxelIndices     = feGet(fe,'voxelsindices',varargin);
      % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
      % val           = val(voxelRowsToKeep,:);
      val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
    end
  case {'dsigrowssubset','diffusionsignaldemeanedinsubsetofrows'}
    % Get the demeaned signal for a subset of rows.
    % Useful for cross-validation.
    %
    % dSig = feGet(fe,'dsigrowssubset',voxelsList);
    dSig = feGet(fe,'dsigdemeaned');
    for vv = 1:length(voxelsList)
      val(feGet(fe,'voxel rows',vv)) = dSig(feGet(fe,'voxel rows',voxelList(vv)));
    end
  case {'psigfiber', 'fiberpsig','fiberpredicted','dsigpredictedfiber'}
    % Predicted signal of fiber alone (demeaned).
    %
    % pSig = feGet(fe,'pSig fiber');
    % pSig = feGet(fe,'pSig fiber',coords);
    % pSig = feGet(fe,'pSig fiber',voxelIndices);
    val = feGet(fe,'Mfiber')*feGet(fe,'fiber weights');
    if ~isempty(varargin)
      % voxelIndices     = feGet(fe,'voxelsindices',varargin);
      % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
      % val           = val(voxelRowsToKeep,:);
      val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
    end
  case {'uniquefibersindicesinroi'}
    % Find the unique fibers indices in the FE roi.
    % Thisis necessary sometimes after changing the number of voxels in an
    % FE structure, as it is performed by feConnectomeReduceVoxels.m
    %
    % FibInRoi = feGet(fe,'uniquefibersinroi');
    % Get all the unique fibers in each voxel
    uniquefvx = fefgGet(feGet(fe,'fibers img'), ...
                        'uniquefibersinvox',     ...
                        feGet(fe,'roi coords'));
    val = [];
    for ivx = 1:length(uniquefvx)
        val = [val; uniquefvx{ivx}];
    end
    val = unique(val);
  case {'weightsinroi'}
    % Find the weights of the fibers in a specified volume.
    %
    % We compute the following values:
    % (1) The number of unique fibers in the volume
    % (2) The weights for the fibers in the roi
    %
    % wFibInRoi = feGet(fe,'weightsinroi');
    % Get all the unique fibers in each voxel
1000     FibInRoi = feGet(fe,'uniquefibersindicesinroi');
1001
1002     % extract the fber weights obtained in a LiFE fit
1003     w   = feGet(fe,'fiber weights');
1004
1005     % Return only the ones for the fibers in this roi
1006     val = w(unique(FibInRoi));
1007
1008   case {'fiberdensity'}
1009     % Fiber density statistics.
1010     %
1011     % Computes the fiber density (how many fibers in each voxel)
1012     %
1013     % We compute the following values:
1014     % (1) The number of fibers in each voxel
1015     % (2) The number of unique fibers with non-zero weights
1016     % (3) The sum of the weights in each voxel
1017     % (4) The mean of the weights in each voxel
1018     % (5) The variance of the weigths in each voxel
1019     %
1020     % pSig = feGet(fe,'fiberdensity');
1021
1022     % Get the unique fibers in each voxel
1023     uniquefvx = fefgGet(feGet(fe,'fibers img'), ...
1024                         'uniquefibersinvox',     ...
1025                         feGet(fe,'roi coords'));
1026
1027     % extract the fber weights obtained in a LiFE fit
1028     w = feGet(fe,'fiber weights');
1029
1030     % Compute the fiber density in three wasy:
1031     % (1) The number of fibers in each voxel
1032     % (2) The number of unique fibers with non-zero weights
1033     % (3) The sum of the weights in each voxel
1034     % (4) The mean of the weights in each voxel
1035     % (5) The variance of the weigths in each voxel
1036     val = nan(length(uniquefvx),5);
1037     for ivx = 1:length(uniquefvx)
1038
1039       % Number of fibers in each voxel
1040       val(ivx,1) = length(uniquefvx{ivx});
1041
1042       % Number of fibers in ech voxel with non-zero weight
1043       val(ivx,2) = length(uniquefvx{ivx}(w(uniquefvx{ivx}) > 0));
1044
1045       % Sum of fiber weights in each voxel
1046       val(ivx,3) = sum(w(uniquefvx{ivx}));
1047
1048       % Mean of fiber weights in each voxel
1049       val(ivx,4) = nanmedian(w(uniquefvx{ivx}));
1050
1051       % Var of fibers in each voxel
1052       val(ivx,5) = nanvar(w(uniquefvx{ivx}));
1053     end
1054
1055   case {'psigfibertest'}
1056     % Predicted signal (demeaned) with a subset of fibers' weights set to 0.
1057     % This can be used to test the loss in RMSE for the connectome when a
1058     % subset of fibers is removed, but the connectome is not fitted again.
1059     %
1060     % pSig = feGet(fe,'pSig fiber test',fiberIndices);
1061     % pSig = feGet(fe,'pSig fiber test',fiberIndices,voxelIndices);
1062     % pSig = feGet(fe,'pSig fiber test',fiberIndices,coords);
1063     if ~isempty(varargin)
1064       val = feGet(fe,'Mfiber')*feGet(fe,'fiber weights test',varargin{1});
1065
1066       % Now select a subset of voxels if requested
1067       if (length(varargin) == 2)
1068         % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1069         % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1070         % val               = val(voxelRowsToKeep,:);
1071         val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin{2})));
1072       end
1073     else
1074       error('[%s] A set f fiber indiced must be passed in. pSig = feGet(fe,''pSig fiber test'',fiberIndices))',mfilename);
1075     end
1076
1077   case {'psigfibertestvoxelwise'}
1078     % Predicted signal (demeaned) with a subset of fibers' weights set to 0.
1079     % This can be used to test the loss in RMSE for the connectome when a
1080     % subset of fibers is removed, but the connectome is not fitted again.
1081     %
1082     % pSig = feGet(fe,'pSig fiber test voxel wise',fiberIndices);
1083     % pSig = feGet(fe,'pSig fiber test voxel wise',fiberIndices,voxelIndices);
1084     % pSig = feGet(fe,'pSig fiber test voxel wise',fiberIndices,coords);
1085
1086     if ~isempty(varargin)
1087       nVoxels = feGet(fe,'nvoxels');
1088       w = feGet(fe,'fiber weights test voxel wise',varargin{1}); % Weights with a subset set to 0
1089       val = cell(nVoxels,1);
1090       for ivox = 1:nVoxels
1091         % Predict the signal.
1092         val{ivox} = feGet(fe,'Mfiber',ivox)*w(ivox,:)';
1093       end
1094
1095      feOpenLocalCluster
1096      % Reorganize the signal into a vector
1097       val = vertcat(val{:})';
1098
1099       % Now select a subset of voxels if requested
1100       if (length(varargin) == 2)
1101         % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1102         % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1103         % val               = val(voxelRowsToKeep,:);
1104         val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin{2})));
1105       end
1106     else
1107       error('[%s] A set f fiber indiced must be passed in. pSig = feGet(fe,''pSig fiber test'',fiberIndices))',mfilename);
1108     end
1109
1110   case {'predictedsignalfull','psigfull'}
1111     % Predicted measured signal from both fiber and iso
1112     %
1113     % pSig = feGet(fe,'pSig full')
1114     % pSig = feGet(fe,'pSig full',coords)
1115     % pSig = feGet(fe,'pSig full',voxelIndices)
1116     val = [feGet(fe,'M fiber'), feGet(fe,'M iso')] * feGet(fe,'full weights');
1117     if ~isempty(varargin)
1118       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1119       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1120       % val           = val(voxelRowsToKeep,:);
1121       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1122     end
1123
1124   case {'fullweights'}
1125     % The fiber and isotropic weights as a long vector
1126     %
1127     % w = feGet(fe,'fullweights')
1128     val = [feGet(fe,'fiber weights'); feGet(fe,'iso weights')];
1129
1130   case {'fiberweightsvoxelwise'}
1131     % The woxels returned by a fit of LiFE by voxel/fiber
1132     %
1133     % w = feGet(fe,'fiberweightsvoxelwise')
1134     val = fe.life.voxfit.weights;
1135
1136   case {'psigfvoxelwise'}
1137     % Predict the diffusion signal for the fiber component
1138     % with the voxel-wise fit of LiFE
1139     %
1140     % pSig = feGet(fe,'psigfvoxelwise')
1141     % pSig = feGet(fe,'psigfvoxelwise',coords)
1142     % pSig = feGet(fe,'psigfvoxelwise',voxelIndices)
1143
1144     if ~isfield(fe.life,'voxfit'),
1145       error('[%s] Cannot find voxel-wise fit.\nTo fit the model voxel-wise run:\nfe = feFitModelByVoxel(fe)\n',mfilename);
1146     end
1147     val = fe.life.voxfit.psig;
1148
1149     % Get a subset of voxels.
1150     if ~isempty(varargin)
1151       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1152       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1153       % val           = val(voxelRowsToKeep,:);
1154       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1155     end
1156
1157   case {'psigfvoxelwisebyvoxel'}
1158     % Predict the diffusion signal for the fiber component
1159     % with the voxel-wise fit of LiFE, return the an array of pSigXnVoxel
1160     %
1161     % pSig = feGet(fe,'psigfvoxelwisebyvoxel')
1162     % pSig = feGet(fe,'psigfvoxelwisebyvoxel',coords)
1163     % pSig = feGet(fe,'psigfvoxelwisebyvoxel',voxelIndices)
1164     nBvecs  = feGet(fe,'nBvecs');
1165     nVoxels = feGet(fe,'n voxels');
1166     val     = reshape(feGet(fe,'psigfvoxelwise'), nBvecs, nVoxels);
1167
1168   case {'totalr2'}
1169     % Return the global R2 (fraction of variance explained) of the full life
1170     % model.
1171     %
1172     % R2 = feGet(fe,'total r2');
1173
1174     %     measured  = feGet(fe,'dsigdemeaned');
1175     %     predicted = feGet(fe,'fiber p sig');
1176     %     val = (1 - (sum((measured - predicted).^2) ./ ...
1177     %                 sum((measured - mean(measured)).^2)));
1178     val = (1 - (sum((feGet(fe,'diffusion signal demeaned') - ...
1179       feGet(fe,'fiber predicted')).^2) ./ ...
1180       sum((feGet(fe,'diffusion signal demeaned') - ...
1181       mean(feGet(fe,'diffusion signal demeaned'))).^2)));
1182
1183   case {'totalr2voxelwise'}
1184     % Return the global R2 (fraction of variance explained) of the full life
1185     % model from a voxel-wise fit.
1186     %
1187     % R2 = feGet(fe,'total r2 vocel wise');
1188
1189     %     measured  = feGet(fe,'dsigdemeaned');
1190     %     predicted = feGet(fe,'p sig f voxel wise');
1191     %     val = (1 - (sum((measured - predicted).^2) ./ ...
1192     %                 sum((measured - mean(measured)).^2)));
1193     val = (1 - (sum((feGet(fe,'diffusion signal demeaned') - ...
1194       feGet(fe,'psigfvoxelwise')').^2) ./ ...
1195       sum((feGet(fe,'diffusion signal demeaned') - ...
1196       mean(feGet(fe,'diffusion signal demeaned'))).^2)));
1197
1198   case {'totpercentvarianceexplained','totpve'}
1199     % Percent variance explained
1200     %
1201     % R2 = feGet(fe,'explained variance')
1202     val = 100 * feGet(fe,'total r2');
1203
1204   case {'rmsetotal','totalrmse'}
1205     % Root mean squared error of the LiFE fit to the whole data
1206     %
1207     % rmse = feGet(fe,'rmse')
1208     val = sqrt(mean((feGet(fe,'diffusion signal demeaned') - ...
1209       feGet(fe,'pSig fiber')).^2));
1210
1211   case {'totalrmsevoxelwise'}
1212     % Root mean squared error of the LiFE fit to the whole data from a
1213     % vocel-wise fit
1214     %
1215     % rmse = feGet(fe,'rmse')
1216     val = sqrt(mean((feGet(fe,'diffusion signal demeaned') - ...
1217       feGet(fe,'pSig f voxelwise')').^2));
1218
1219   case {'ressigfiber'}
1220     % Residual signal fiber prediction - measured_demeaned.
1221     %
1222     % res = feGet(fe,'res sig fiber')
1223     val = (feGet(fe,'dsigdemeaned')    - feGet(fe,'psig fiber'));
1224     if ~isempty(varargin)
1225       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1226       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1227       % val              = val(voxelRowsToKeep,:);
1228       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1229     end
1230
1231   case {'ressigfull'}
1232     % Residual signal full model prediction - measured signal.
1233     %
1234     % res = feGet(fe,'res sig full');
1235     % res = feGet(fe, 'res sig full',coords);
1236     % res = feGet(fe, 'res sig full',voxelIndex);
1237     val = (feGet(fe,'dsig full')    - feGet(fe,'psig full')');
1238     if ~isempty(varargin)
1239       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1240       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1241       % val           = val(voxelRowsToKeep,:);
1242       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1243     end
1244
1245   case {'ressigfullvoxelwise'}
1246     % Residual signal full model prediction from a multi-voxel fit.
1247     %
1248     % res = feGet(fe,'res sig full voxfit');
1249     % res = feGet(fe, 'res sig full voxfit',coords);
1250     % res = feGet(fe, 'res sig full voxfit',voxelIndex);
1251     %tic,val      = feGet(fe,'dsig demeaned') - feGet(fe,'psigfvoxelwise') + feGet(fe,'dsigiso');toc
1252     val      = feGet(fe,'dsig full') - feGet(fe,'psigfvoxelwise')';
1253     if ~isempty(varargin)
1254       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1255       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1256       % val           = val(voxelRowsToKeep,:);
1257       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1258     end
1259
1260   case {'fiberressigwithmean'}
1261     % Residual signal fiber model prediction - demeaned measured signal
1262     % with added mean signal. VECTOR FORM.
1263     %
1264     % This is used to reconstruct an image (volume) to be used for the
1265     % refinement process.
1266     %
1267     % res = feGet(fe,'fiber res sig with mean');
1268
1269     % predicted = feGet(fe,'psig fiber');
1270     % measured  = feGet(fe,'dsigdemeaned');
1271     % val = (measured_full - predicted demeaned);
1272     val = (feGet(fe,'dsig full')' - feGet(fe,'psig fiber'));
1273
1274     if ~isempty(varargin)
1275       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1276       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1277       % val           = val(voxelRowsToKeep,:);
1278       val = val(feGet(fe,'voxel rows',feGet(fe,'voxelsindices',varargin)));
1279     end
1280
1281   case {'predictedfibersignalvoxel','psigfvox'}
1282     % Predicted signal by the fiber model in a set of voxels.
1283     %
1284     % Vox subfield stores per voxel within the VOI
1285     % The pSig has size of the dwi.
1286     % It is stored as val = pSig(X,Y,Z,Theta)
1287     %
1288     % pSig = feGet(fe, 'pSig fiber by voxel');
1289     % pSig = feGet(fe, 'pSig fiber by voxel',coords);
1290     % pSig = feGet(fe, 'pSig fiber by voxel',voxelIndex);
1291     nBvecs  = feGet(fe,'nBvecs');
1292     nVoxels = feGet(fe,'n voxels');
1293     val     = reshape(feGet(fe,'pSig fiber'), nBvecs, nVoxels);
1294     val     = val(:,feGet(fe,'return voxel indices',varargin));
1295
1296   case {'predictedfullsignalvoxel','psigfullvox'}
1297     % Predicted signal by the full model in a set of voxeles.
1298     %
1299     % Vox subfield stores per voxel within the VOI
1300     % The pSig has size of the dwi.
1301     % It is stored as val = pSig(X,Y,Z,Theta)
1302     %
1303     % pSig = feGet(fe, 'pSig full by voxel');
1304     % pSig = feGet(fe, 'pSig full by voxel',coords);
1305     % pSig = feGet(fe, 'pSig full by voxel',voxelIndex);
1306     nBvecs  = feGet(fe,'nBvecs');
1307     nVoxels = feGet(fe,'n voxels');
1308     val     = reshape(feGet(fe,'pSig full'), nBvecs, nVoxels);
1309
1310   case {'voxelr2','r2vox','voxr2','r2byvoxel'}
1311     % Return a column vector of the proportion of variance explained in
1312     % each voxel.
1313     %
1314     % R2byVox = feGet(fe,'voxr2');
1315     % R2byVox = feGet(fe,'voxr2',coords);
1316     measured  = feGet(fe,'dSig demeaned by voxel');
1317     predicted = feGet(fe,'pSig f vox');
1318     nBvecs    = feGet(fe,'nBvecs');
1319     val       = (1 - (sum((measured - predicted).^2) ./ ...
1320       sum((measured - repmat(mean(measured), nBvecs,1)).^2)));
1321     val       = val(feGet(fe,'return voxel indices',varargin));
1322
1323   case {'voxelr2zero','r2voxzero','voxr2zero','r2byvoxelzero'}
1324     % Return a column vector of the proportion of variance explained in
1325     % each voxel. (Normalized to the squared diffusion signal in each voxel)
1326     %
1327     % R2byVox = feGet(fe,'voxr2zero');
1328     % R2byVox = feGet(fe,'voxr2zero',coords);
1329     measured  = feGet(fe,'dSig demeaned by voxel');
1330     predicted = feGet(fe,'pSig f vox');
1331     val       = (1 - (sum((measured - predicted).^2) ./ sum(measured.^2)));
1332     val       = val(feGet(fe,'return voxel indices',varargin));
1333
1334   case {'voxelvarianceexplained','varexpvox','voxvarexp','varexpbyvoxel'}
1335     % Return the percent of varince explained in each voxel.
1336     %
1337     % R2byVox = feGet(fe,'var exp by voxel');
1338     % R2byVox = feGet(fe,'var exp by voxel',coords);
1339     val = 100.*feGet(fe,'voxr2');
1340     val = val(feGet(fe,'return voxel indices',varargin));
1341
1342   case {'voxelr2voxelwise','r2voxvoxelwise','voxr2voxelwise'}
1343     % Return a column vector of the proportion of variance explained in
1344     % each voxel.
1345     %
1346     % R2byVox = feGet(fe,'voxr2voxelwise');
1347     % R2byVox = feGet(fe,'voxr2voxewise',coords);
1348     measured  = feGet(fe,'dSig demeaned by voxel');
1349     predicted = feGet(fe,'psig f voxel wise by voxel');
1350     nBvecs    = feGet(fe,'nBvecs');
1351     val       = (1 - (sum((measured - predicted).^2) ./ ...
1352       sum((measured - repmat(mean(measured), nBvecs,1)).^2)));
1353     val       = val(feGet(fe,'return voxel indices',varargin));
1354
1355   case {'voxelr2zerovoxelwise','voxr2zerovoxelwise'}
1356     % Return a column vector of the proportion of variance explained in
1357     % each voxel. (Normalized to the squared diffusion signal in each voxel)
1358     %
1359     % R2byVox = feGet(fe,'voxr2zerovoxelwise');
1360     % R2byVox = feGet(fe,'voxr2zerovoxelwise',coords);
1361     measured  = feGet(fe,'dSig demeaned by voxel');
1362     predicted = feGet(fe,'psig f voxel wise by voxel');
1363     val       = (1 - (sum((measured - predicted).^2) ./ sum(measured.^2)));
1364     val       = val(feGet(fe,'return voxel indices',varargin));
1365
1366   case {'voxelvarianceexplainedvoxelwise','varexpvoxvoxelwise'}
1367     % Return the percent of varince explained in each voxel.
1368     %
1369     % R2byVox = feGet(fe,'var exp by voxel');
1370     % R2byVox = feGet(fe,'var exp by voxel',coords);
1371     val = 100.*feGet(fe,'voxr2voxelwise');
1372     val = val(feGet(fe,'return voxel indices',varargin));
1373
1374   case {'dsigdemeanedbyvoxel','dsigdemeanedvox'}
1375     % Demeaned diffusion signal in each voxel
1376     %
1377     % dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel');
1378     % dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',coords);
1379     % dSigByVoxel = feGet(fe,'dsigdemeaned by Voxel',vxIndex);
1380     nBvecs  = feGet(fe,'nBvecs');
1381     nVoxels = feGet(fe,'n voxels');
1382     val     = reshape(feGet(fe,'dsigdemeaned'), nBvecs, nVoxels);
1383     val     = val(:,feGet(fe,'return voxel indices',varargin));
1384
1385   case {'dsigfullbyvoxel','dsigfullvox','voxdsigfull'}
1386     % Full (measured) signal in each voxel
1387     %
1388     % dSigByVoxel = feGet(fe,'dSig full by Voxel');
1389     % dSigByVoxel = feGet(fe,'dSig full by Voxel',coords);
1390     % dSigByVoxel = feGet(fe,'dSig full by Voxel',vxIndex);
1391     nBvecs  = feGet(fe,'nBvecs');
1392     nVoxels = feGet(fe,'n voxels');
1393     val     = reshape(feGet(fe,'dSig full'), nBvecs, nVoxels);
1394     val    = val(:,feGet(fe,'return voxel indices',varargin))';
1395
1396   case {'voxelrmse','voxrmse'}
1397     % A volume of RMSE values
1398     %
1399     % RMSE = feGet(fe,'vox rmse')
1400     % RMSE = feGet(fe,'vox rmse',coords)
1401     % RMSE = feGet(fe,'vox rmse',vxIndex)
1402     measured  = feGet(fe,'dsigdemeaned by voxel');
1403     predicted = feGet(fe,'pSig f vox');
1404     val       = sqrt(mean((measured - predicted).^2,1));
1405     val       = val(feGet(fe,'voxelsindices',varargin));
1406
1407   case {'voxelrmsevoxelwise','voxrmsevoxelwise'}
1408     % A volume of RMSE values optained with the voxel-wise (voxelwise) fit.
1409     %
1410     % RMSE = feGet(fe,'vox rmse voxelwise')
1411     % RMSE = feGet(fe,'vox rmse voxelwise',coords)
1412     % RMSE = feGet(fe,'vox rmse voxelwise',vxIndex)
1413     measured  = feGet(fe,'dsigdemeaned by voxel');
1414     predicted = feGet(fe,'pSig f voxel wise by voxel');
1415
1416     val       = sqrt(mean((measured - predicted).^2,1));
1417     val       = val(feGet(fe,'voxelsindices',varargin));
1418
1419   case {'voxelrmsetest','voxrmsetest'}
1420     % A volume of RMSE values with a subset of fibers' weights set to 0.
1421     %
1422     % RMSE = feGet(fe,'vox rmse',fiberIndices)
1423     % RMSE = feGet(fe,'vox rmse',fiberIndices,coords)
1424     % RMSE = feGet(fe,'vox rmse',fiberIndices,voxelIndex)
1425     measured  = feGet(fe,'dsigdemeaned by voxel');
1426     % Reshape the predicted signal by voxles
1427     predicted = reshape(feGet(fe,'pSig fiber test',varargin{1}), feGet(fe,'nBvecs'), feGet(fe,'nVoxels'));
1428     val       = sqrt(mean((measured - predicted).^2,1));
1429
1430     if length(varargin) == 2
1431       val       = val(feGet(fe,'voxelsindices',varargin));
1432     end
1433
1434   case {'residualsignalfibervoxel','resfibervox'}
1435     % Fibers' residual signal by voxel
1436     %
1437     % res = feGet(fe,'res sig fiber vox')
1438     % res = feGet(fe,'res sig fiber vox',coords)
1439     % res = feGet(fe,'res sig fiber vox',vxIndex)
1440     nBvecs  = feGet(fe,'nBvecs');
1441     nVoxels = feGet(fe,'n voxels');
1442     val     = reshape(feGet(fe,'res sig fiber'), nBvecs, nVoxels);
1443     val     = val(:,feGet(fe,'return voxel indices',varargin))';
1444
1445   case {'residualsignalfullvoxel','resfullvox'}
1446     % Full (measured) residual signal by voxel
1447     %
1448     % res = feGet(fe,'res sig full vox')
1449     % res = feGet(fe,'res sig full vox',coords)
1450     % res = feGet(fe,'res sig full vox',vxIndex)
1451     nBvecs  = feGet(fe,'nBvecs');
1452     nVoxels = feGet(fe,'n voxels');
1453     val     = reshape(feGet(fe,'res sig full'), nBvecs, nVoxels);
1454     val     = val(:,feGet(fe,'return voxel indices',varargin))';
1455
1456   case {'fiberressigwithmeanvoxel'}
1457     % Residual signal fiber model prediction - demeaned measured signal
1458     % with added mean signal. VOXEL FORM (nBvecs x nVoxel).
1459     %
1460     % This is used to reconstruct an image (volume) to be used for the
1461     % refinement process.
1462     %
1463     % res = feGet(fe,'fiber res sig with mean');
1464
1465     % predicted = feGet(fe,'psig fiber');
1466     % measured  = feGet(fe,'dsigdemeaned');
1467     % val = (measured     - predicted) + (measured_full - measured);
1468     val     = feGet(fe,'fiberressigwithmean');
1469     nBvecs  = feGet(fe,'nBvecs');
1470     nVoxels = feGet(fe,'n voxels');
1471     val     = reshape(val, nBvecs, nVoxels);
1472
1473     if ~isempty(varargin)
1474       % voxelIndices     = feGet(fe,'voxelsindices',varargin);
1475       % voxelRowsToKeep  = feGet(fe,'voxel rows',voxelIndices);
1476       % val              = val(voxelRowsToKeep,:);
1477       val = val(:, feGet(fe,'return voxel indices',varargin));
1478     end
1479
1480   case {'fiberressigwithmeanvox','resfibermeanvox'}
1481     % Fibers' residual signal by voxel with mean signal added (with added
1482     % isotropic component).
1483     %
1484     % This is used to compute the residual signal for the refinement.
1485     %
1486     % res = feGet(fe,'fiber res sig with mean vox')
1487     % res = feGet(fe,'fiber res sig with mean vox',coords)
1488     % res = feGet(fe,'fiber res sig with mean vox',vxIndex)
1489     nBvecs  = feGet(fe,'nBvecs');
1490     nVoxels = feGet(fe,'n voxels');
1491     val     = reshape(feGet(fe,'fiber res sig with mean'), nBvecs, nVoxels);
1492     val     = val(:,feGet(fe,'return voxel indices',varargin))';
1493
1494   case {'voxelsindices','returnvoxelindices','voxelindexes''returnvoxelindexes'}
1495     % Given an VOI or a set of indices to voxels returns the indices of the matching voxels inside the big
1496     % volume, which ordinarily represents the full connectome.
1497     %
1498     % voxelIndices = feGet(fe,'voxelsindices',coords)
1499     % voxelIndices = feGet(fe,'voxelsindices',voxelIndices)
1500     %                IMPORTANT: Indices MUST be a column vector for this
1501     %                code to work.
1502     %
1503     % coords is a Nx3 set of coordinates in image space
1504     % voxelIndices is a vector of 1's and 0's, there is a one for each
1505     % location the the connectome coordinates for which there is a match in
1506     % the coords
1507     %
1508     varargin = varargin{1};
1509     if (~isempty(varargin))
1510       if (size(varargin{1},2) == 3)
1511         % If a set of coordinates were passed in we return the indices.
1512         val = logical(feGet(fe,'find voxels',varargin{1}));
1513       else
1514         % If indices were passed in, we sort and return them.
1515         val = sort(varargin{1});
1516       end
1517     else
1518       % If no coordinates were passed at all, we return all the indices.
1519       val = true(feGet(fe,'n voxels'),1);
1520     end
1521
1522   case {'findvoxels','findvoxelindexes','findvoxelsinconnectome','findvoxelsinconnectomeroi', ...
1523       'voxel2index','coords2index'}
1524     % Given an VOI finds the indices of the matching voxels inside the big
1525     % volume, which ordinarily represents the full connectome.
1526     %
1527     % foundVoxels = feGet(fe,'find voxels',coords)
1528     %
1529     % coords is a Nx3 set of coordinates in image space
1530     % foundVoxels is a vector of 1's and 0's, there is a one for each
1531     % location the the connectome coordinates for which there is a match in
1532     % the coords
1533
1534     % Compute the values for a subset of voxels
1535     if isempty(varargin)
1536       % If no coordinates were passed at all, we return all the indices.
1537       val = ones(feGet(fe,'n voxels'),1);
1538     else
1539       % The stored coordinates are at a resolution of the image, typically
1540       % 2mm isotropic.  The VOI should also be in image resolution.
1541       % ---- Franco:
1542       % This is how I had it. I think it is worng:
1543       % val = ismember(feGet(fe,'roi coords'), varargin{1}, 'rows'); % This is slow
1544       % This is hwo I think it should be:
1545       [~,val] = ismember(varargin{1}, feGet(fe,'roi coords'),'rows'); % This is slow
1546     end
1547
1548   case {'voxelcoords2voxelrows','coords2rows'}
1549     % Given a set of VOI coords finds the row numbers of the Model matrix
1550     % (or equivalently the dSig vector) that represent the data for this
1551     % set of VOI coords.
1552     %
1553     % foundVoxels = feGet(fe,'coords 2 rows',coords)
1554     %
1555     % coords      - a Nx3 set of coordinates in image space
1556     % foundVoxels - a binary vector that is 1 for each Model matrix row
1557     %               that corresponds to at least one of the coords.
1558     val = feGet(fe,'voxel rows',find(feGet(fe,'find voxels',varargin{1})));
1559
1560     % ------ Spatial coordinate transforms for voxels and fg to coordinate frames
1561   case {'xformimg2acpc','xform2acpc','img2acpc','img2acpcxform'}
1562     % Quaternian transformation from IMAGE space to ACPC space.
1563     %
1564     % xform = feGet(fe,'xform')
1565     val = fe.life.xform.img2acpc;
1566   case {'xformacpc2img','xform2img','acpc2img','acpc2imgxform'}
1567     % Quaternian transformation from ACPC space to IMAGE space.
1568     %
1569     % xform = feGet(fe,'xform')
1570     val = fe.life.xform.acpc2img;
1571   case {'volumesize','dims','dim','imagedim'}
1572     % Dimensions of the DW volume.
1573     %
1574     % dim = feGet(fe,'dims')
1575     val = fe.life.imagedim;
1576   case {'mapsize'}
1577     % Dimensions of the maps of parameters and results.
1578     %
1579     % dims = feGet(fe, 'mapsize')
1580     val = fe.life.imagedim(1:3);
1581
1582   case {'anatomyfile'}
1583     % Path to the 3D Anatomy Volume.
1584     % anatomyfile = feGet(fe, 'anatomy file')
1585     val = fe.path.anatomy;
1586   case 'dtfile'
1587     % Diffusion weighted file used for testing results
1588     % dtfile = feGet(fe,'dtfile')
1589      val = fe.path.dtfile;
1590
1591   otherwise
1592     help('feGet')
1593     fprintf('[feGet] Unknown parameter << %s >>...\n',param);
1594     keyboard
1595 end
1596
1597 end % END MAIN FUNCTION