function s_ms_plots_across_connectomes(trackingType)
% Load a connectome used for the Manuscript and plot some statistics on the
% fibers.
%
% See also: s_life_track.m,  s_lifeTestTractographyModels.m, 
%
% Franco (c) Stanford VISTA Team 2012

%% Load the data
% Get the data path
dataDir  = msPaths('data');

% trackingType  = 'deterministic'; 
switch trackingType
  case {'deterministic'}
    connectomeFile = { ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000.mat',...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000.mat', ...
      'fg_whole_brain_FACT_RK4.mat', ...
      'fg_whole_brain_TEND_RK4.mat', ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000_pointy.mat',...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000_pointy.mat', ...
      'fg_whole_brain_FACT_RK4_pointy.mat', ...
      'fg_whole_brain_TEND_RK4_pointy.mat', ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000_fat.mat', ...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000_fat.mat',...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000_fat.mat', ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000_fat.mat', ...
      'fg_whole_brain_FACT_RK4_fat.mat', ...
      'fg_whole_brain_TEND_RK4_fat.mat'}; 
    connectomeFile2 = { ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000_2.mat', ...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000_2.mat', ...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000_2.mat' ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000_2.mat', ...
      'fg_whole_brain_FACT_RK4.mat', ...
      'fg_whole_brain_TEND_RK4.mat', ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000_2_pointy.mat', ...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000_2_pointy.mat', ...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000_2_pointy.mat' ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000_2_pointy.mat', ...
      'fg_whole_brain_FACT_RK4_pointy.mat', ...
      'fg_whole_brain_TEND_RK4_pointy.mat', ...
      'mrtrix_whole_brain_lmax2_stream_ntracks_200000_2_fat.mat', ...
      'mrtrix_whole_brain_lmax4_stream_ntracks_200000_2_fat.mat', ...
      'mrtrix_whole_brain_lmax8_stream_ntracks_200000_2_fat.mat' ...
      'mrtrix_whole_brain_lmax16_stream_ntracks_200000_2_fat.mat', ...
      'fg_whole_brain_FACT_RK4_fat.mat', ...
      'fg_whole_brain_TEND_RK4_fat.mat'};
    
  case {'probabilistic'}
    connectomeFile = { ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000.mat',...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000.mat', ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000_pointy.mat',...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000_pointy.mat', ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000_fat.mat', ...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000_fat.mat',...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000_fat.mat', ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000_fat.mat'};
    connectomeFile2 = { ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000_2.mat', ...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000_2.mat', ...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000_2.mat' ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000_2.mat', ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000_2_pointy.mat', ...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000_2_pointy.mat', ...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000_2_pointy.mat' ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000_2_pointy.mat', ...
      'mrtrix_whole_brain_lmax2_prob_ntracks_200000_2_fat.mat', ...
      'mrtrix_whole_brain_lmax4_prob_ntracks_200000_2_fat.mat', ...
      'mrtrix_whole_brain_lmax8_prob_ntracks_200000_2_fat.mat' ...
      'mrtrix_whole_brain_lmax16_prob_ntracks_200000_2_fat.mat'};
  otherwise
    keyboard
end

stats = ... % Global model fit
    {'voxr2', 'voxrmse', 'voxrmseratio', ...
     'voxrmsevoxelwise','voxr2voxelwise','voxrmseratiovoxelwise', ...    
     'voxrmsedata','voxr2data'};
   
%% Run over the stats and files and compute
for is = 1:length(stats)
  % Load one file at the time and make a histgram plot
  for a = 1:length(connectomeFile)
    % Load the fe structure
    for irep = 1:2
      if (irep == 1)
        fileName = (fullfile(dataDir,connectomeFile{a}));
      else
        fileName = (fullfile(dataDir,connectomeFile2{a}));
      end
      fprintf('[%s] Loading fe structure...\n%s\n',mfilename,fileName)
      load(fileName);
      val(irep) = nanmedian(feGetRep(fe,stats{is}));
    end
    
    % Save it into a structure
    s(a).path  = dataDir;
    s(a).data1 = connectomeFile{a};
    s(a).data2 = connectomeFile2{a};
    s(a).(stats{is}).vals = val;
    s(a).(stats{is}).m    = nanmedian(val);
    s(a).(stats{is}).ste  =  nanstd(val)./sqrt(2);
    s(a).(stats{is}).std  =  nanstd(val);
  end
end

fprintf('[%s] saving file: %s ...\n',fullfile(feGet(fe,'savedir'),sprintf('statistics_%s.mat',trackingType)));
save(fullfile(feGet(fe,'savedir'),sprintf('statistics_%s.mat',trackingType)),'s','-v7.3');


%% Now make a plot
stats_names = fieldnames(s);
ylims = {[.05 .45],[25 35],[0.8 1.2], [25 35], [.05 .45], [.8 1.2], [25 35],[.05 .45]};
for is = 1:length(stats_names)-3 % These are all the statistcts we computed
  Sm = []; Sse = [];
  % We collect all the statistcs across files
  for ii = 1:length(s)             % These are the files for which we computed the statistcs
    Sm = [Sm,  s(ii).(stats_names{is+3}).m];
    Sse = [Sse,s(ii).(stats_names{is+3}).ste];
  end
  mrvNewGraphWin([trackingType,'-',stats_names{is + 3}]);
  bar(Sm,'k'); hold on
  for ii = 1:length(Sm)
  plot([ii ii],[Sm(ii) - 2*Sse(ii) Sm(ii) + 2*Sse(ii)],'r-')
  end
  set(gca, 'box', 'off', ...
    'TickDir','out', 'TickLen',[.015 0],...
    'XTick',1:length(s), 'XTickLabel',{'lmax2','lmax4','lmax8','lmax16',...
     'FACT','TEND','lmax2p','lmax4p','lmax8p','lmax16p','FACTp','TENDp', ...
     'lmax2f','lmax4f','lmax8f','lmax16f','FACTf','TENDf'}, ...
     'Ylim',ylims{is})
end


